- name: Enviar archivos al VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # Usamos un patrón más directo
          source: "dist/examen2-despliegue/browser/*"
          target: "/var/www/html/examen"
          strip_components: 3
# fin
