name: Deploy Angular
on:
  push:
    [cite_start]branches: [ main ] # Se activa al subir a la rama main [cite: 42]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        [cite_start]run: npm ci # [cite: 44]

      - name: Compilar proyecto
        [cite_start]run: npm run build -- --configuration production # [cite: 24, 45]

      - name: Enviar archivos al VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # CUIDADO: Verifica el nombre de tu carpeta en /dist/
          [cite_start]source: "dist/Nombre_De_Tu_Proyecto/browser/*" # [cite: 46]
          [cite_start]target: "/var/www/html/examen" # 
          strip_components: 3
